/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary-container": "#b0aef9",
        outline: "#918fa1",
        "surface-bright": "#393939",
        "inverse-primary": "#4d44e3",
        "on-secondary-fixed-variant": "#413f82",
        "on-secondary-fixed": "#140f54",
        "on-primary": "#1d00a5",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed": "#351000",
        "surface-container-low": "#1c1b1b",
        "primary-fixed-dim": "#c3c0ff",
        "outline-variant": "#464555",
        "secondary-fixed-dim": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "on-error-container": "#ffdad6",
        primary: "#c3c0ff",
        "surface-container-lowest": "#0e0e0e",
        "primary-container": "#4f46e5",
        "surface-container": "#201f1f",
        background: "#131313",
        "on-surface-variant": "#c7c4d8",
        "tertiary-container": "#a44100",
        error: "#ffb4ab",
        "on-tertiary-container": "#ffd2be",
        "on-tertiary": "#571f00",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-fixed-variant": "#7b2f00",
        tertiary: "#ffb695",
        "tertiary-fixed-dim": "#ffb695",
        "on-secondary": "#2a276a",
        "on-primary-container": "#dad7ff",
        "surface-container-highest": "#353534",
        "secondary-container": "#413f82",
        "inverse-on-surface": "#313030",
        "tertiary-fixed": "#ffdbcc",
        "on-background": "#e5e2e1",
        secondary: "#c3c0ff",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed": "#e2dfff",
        "on-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "on-error": "#690005",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "surface-tint": "#c3c0ff",
        surface: "#131313",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
